// This file is auto-generated by @hey-api/openapi-ts

export const $EventMessageTypeModel = {
    enum: ['Default', 'Info', 'Error', 'Success', 'Warning'],
    type: 'string'
} as const;

export const $NotificationHeaderModel = {
    required: ['category', 'message', 'type'],
    type: 'object',
    properties: {
        message: {
            type: 'string'
        },
        category: {
            type: 'string'
        },
        type: {
            '$ref': '#/components/schemas/EventMessageTypeModel'
        }
    },
    additionalProperties: false
} as const;

export const $OrganiseRequest = {
    required: ['contentTypes', 'dataTypes', 'mediaTypes', 'memberTypes'],
    type: 'object',
    properties: {
        dataTypes: {
            type: 'boolean'
        },
        contentTypes: {
            type: 'boolean'
        },
        mediaTypes: {
            type: 'boolean'
        },
        memberTypes: {
            type: 'boolean'
        }
    },
    additionalProperties: false
} as const;

export const $OrganiseResponse = {
    required: ['error', 'message'],
    type: 'object',
    properties: {
        error: {
            type: 'boolean',
            readOnly: true
        },
        message: {
            type: 'string',
            readOnly: true
        }
    },
    additionalProperties: false
} as const;