// This file is auto-generated by @hey-api/openapi-ts

export const EventMessageTypeModelSchema = {
    enum: ['Default', 'Info', 'Error', 'Success', 'Warning'],
    type: 'string'
} as const;

export const NotificationHeaderModelSchema = {
    required: ['category', 'message', 'type'],
    type: 'object',
    properties: {
        message: {
            type: 'string'
        },
        category: {
            type: 'string'
        },
        type: {
            '$ref': '#/components/schemas/EventMessageTypeModel'
        }
    },
    additionalProperties: false
} as const;

export const OrganiseInfoModelSchema = {
    required: ['alias', 'description', 'name'],
    type: 'object',
    properties: {
        alias: {
            type: 'string'
        },
        name: {
            type: 'string'
        },
        description: {
            type: 'string'
        }
    },
    additionalProperties: false
} as const;

export const OrganiseInfoResponseSchema = {
    required: ['contentTypes', 'dataTypes', 'mediaTypes', 'memberTypes'],
    type: 'object',
    properties: {
        dataTypes: {
            type: 'array',
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/OrganiseInfoModel'
                    }
                ]
            }
        },
        contentTypes: {
            type: 'array',
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/OrganiseInfoModel'
                    }
                ]
            }
        },
        mediaTypes: {
            type: 'array',
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/OrganiseInfoModel'
                    }
                ]
            }
        },
        memberTypes: {
            type: 'array',
            items: {
                oneOf: [
                    {
                        '$ref': '#/components/schemas/OrganiseInfoModel'
                    }
                ]
            }
        }
    },
    additionalProperties: false
} as const;

export const OrganiseRequestSchema = {
    required: ['contentTypes', 'dataTypes', 'mediaTypes', 'memberTypes'],
    type: 'object',
    properties: {
        dataTypes: {
            type: 'boolean'
        },
        contentTypes: {
            type: 'boolean'
        },
        mediaTypes: {
            type: 'boolean'
        },
        memberTypes: {
            type: 'boolean'
        }
    },
    additionalProperties: false
} as const;

export const OrganiseResponseSchema = {
    required: ['error', 'message'],
    type: 'object',
    properties: {
        error: {
            type: 'boolean',
            readOnly: true
        },
        message: {
            type: 'string',
            readOnly: true
        }
    },
    additionalProperties: false
} as const;