// This file is auto-generated by @hey-api/openapi-ts

import type { Client, Options as Options2, TDataShape } from './client';
import { client } from './client.gen';
import type { GetUmbracoBackOfficeOrganiserApiV1InfoData, GetUmbracoBackOfficeOrganiserApiV1InfoResponses, PostUmbracoBackOfficeOrganiserApiV1OrganiseData, PostUmbracoBackOfficeOrganiserApiV1OrganiseErrors, PostUmbracoBackOfficeOrganiserApiV1OrganiseResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = Options2<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class BackOfficeOrganiser {
    public static getUmbracoBackOfficeOrganiserApiV1Info<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoBackOfficeOrganiserApiV1InfoData, ThrowOnError>) {
        return (options?.client ?? client).get<GetUmbracoBackOfficeOrganiserApiV1InfoResponses, unknown, ThrowOnError>({
            url: '/umbraco/BackOfficeOrganiser/api/v1/info',
            ...options
        });
    }
    
    public static postUmbracoBackOfficeOrganiserApiV1Organise<ThrowOnError extends boolean = true>(options?: Options<PostUmbracoBackOfficeOrganiserApiV1OrganiseData, ThrowOnError>) {
        return (options?.client ?? client).post<PostUmbracoBackOfficeOrganiserApiV1OrganiseResponses, PostUmbracoBackOfficeOrganiserApiV1OrganiseErrors, ThrowOnError>({
            url: '/umbraco/BackOfficeOrganiser/api/v1/organise',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
}
