// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from '@hey-api/client-fetch';
import type { GetUmbracoBackOfficeOrganiserApiV1InfoData, GetUmbracoBackOfficeOrganiserApiV1InfoResponse, PostUmbracoBackOfficeOrganiserApiV1OrganiseData, PostUmbracoBackOfficeOrganiserApiV1OrganiseResponse, PostUmbracoBackOfficeOrganiserApiV1OrganiseError } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

export class BackOfficeOrganiserService {
    public static getUmbracoBackOfficeOrganiserApiV1Info<ThrowOnError extends boolean = true>(options?: Options<GetUmbracoBackOfficeOrganiserApiV1InfoData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).get<GetUmbracoBackOfficeOrganiserApiV1InfoResponse, unknown, ThrowOnError>({
            url: '/umbraco/BackOfficeOrganiser/api/v1/info',
            ...options
        });
    }
    
    public static postUmbracoBackOfficeOrganiserApiV1Organise<ThrowOnError extends boolean = true>(options?: Options<PostUmbracoBackOfficeOrganiserApiV1OrganiseData, ThrowOnError>) {
        return (options?.client ?? _heyApiClient).post<PostUmbracoBackOfficeOrganiserApiV1OrganiseResponse, PostUmbracoBackOfficeOrganiserApiV1OrganiseError, ThrowOnError>({
            url: '/umbraco/BackOfficeOrganiser/api/v1/organise',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options?.headers
            }
        });
    }
    
}