// This file is auto-generated by @hey-api/openapi-ts

import type { Client, ClientMeta, Options as Options2, RequestResult, TDataShape } from './client';
import { client } from './client.gen';
import type { GetInfoData, GetInfoErrors, GetInfoResponses, PostOrganiseData, PostOrganiseErrors, PostOrganiseResponses } from './types.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean, TResponse = unknown> = Options2<TData, ThrowOnError, TResponse> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

export class BackOfficeOrganiser {
    public static getInfo<ThrowOnError extends boolean = true>(options?: Options<GetInfoData, ThrowOnError>): RequestResult<GetInfoResponses, GetInfoErrors, ThrowOnError> {
        return (options?.client ?? client).get<GetInfoResponses, GetInfoErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/BackOfficeOrganiser/api/v1/info',
            ...options
        });
    }
    
    public static postOrganise<ThrowOnError extends boolean = true>(options: Options<PostOrganiseData, ThrowOnError>): RequestResult<PostOrganiseResponses, PostOrganiseErrors, ThrowOnError> {
        return (options.client ?? client).post<PostOrganiseResponses, PostOrganiseErrors, ThrowOnError>({
            security: [{ scheme: 'bearer', type: 'http' }],
            url: '/umbraco/BackOfficeOrganiser/api/v1/organise',
            ...options,
            headers: {
                'Content-Type': 'application/json',
                ...options.headers
            }
        });
    }
}
