// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type { PostUmbracoBackofficeorganiserApiOrganiseData, PostUmbracoBackofficeorganiserApiOrganiseResponse } from './types.gen';

/**
 * @param data The data for the request.
 * @param data.requestBody
 * @returns unknown Success
 * @throws ApiError
 */
export const postUmbracoBackofficeorganiserApiOrganise = (data: PostUmbracoBackofficeorganiserApiOrganiseData = {}): CancelablePromise<PostUmbracoBackofficeorganiserApiOrganiseResponse> => { return __request(OpenAPI, {
    method: 'POST',
    url: '/umbraco/backofficeorganiser/api/organise',
    body: data.requestBody,
    mediaType: 'application/json'
}); };