// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: 'http://localhost:54813/' | (string & {});
};

export type OrganiseInfoModel = {
    alias: string;
    name: string;
    description: string;
};

export type OrganiseInfoResponse = {
    dataTypes: Array<OrganiseInfoModel>;
    contentTypes: Array<OrganiseInfoModel>;
    mediaTypes: Array<OrganiseInfoModel>;
    memberTypes: Array<OrganiseInfoModel>;
};

export type OrganiseRequest = {
    dataTypes: boolean;
    contentTypes: boolean;
    mediaTypes: boolean;
    memberTypes: boolean;
};

export type OrganiseResponse = {
    error: boolean;
    message: null | string;
};

export type GetInfoData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/umbraco/BackOfficeOrganiser/api/v1/info';
};

export type GetInfoErrors = {
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type GetInfoResponses = {
    /**
     * OK
     */
    200: OrganiseInfoResponse;
};

export type GetInfoResponse = GetInfoResponses[keyof GetInfoResponses];

export type PostOrganiseData = {
    body: OrganiseRequest;
    path?: never;
    query?: never;
    url: '/umbraco/BackOfficeOrganiser/api/v1/organise';
};

export type PostOrganiseErrors = {
    /**
     * Bad Request
     */
    400: OrganiseResponse;
    /**
     * The resource is protected and requires an authentication token
     */
    401: unknown;
};

export type PostOrganiseError = PostOrganiseErrors[keyof PostOrganiseErrors];

export type PostOrganiseResponses = {
    /**
     * OK
     */
    200: OrganiseResponse;
};

export type PostOrganiseResponse = PostOrganiseResponses[keyof PostOrganiseResponses];
