name: Release
on:
  pull_request:
    branches: "main"
    types: [ closed ]
  workflow_dispatch:
jobs:
  build_release:
    permissions:
      contents: write
    uses: jcdcdev/jcdcdev.Github.UmbracoSimpleDeploy/.github/workflows/build-release-template.yml@main
    with:
      project-name: 'Umbraco.Community.BackOfficeOrganiser'
      project-path: './src/Umbraco.Community.BackOfficeOrganiser/Umbraco.Community.BackOfficeOrganiser.csproj'
      npm-enabled: true
      npm-working-dir: './src/Umbraco.Community.BackOfficeOrganiser.Client/'
      npm-run-command: 'build'
      deploy: true
      color-primary: '#113537'
      color-secondary: '#8A897C'
      color-tertiary: '#A4F9C8'
    secrets:
      nuget-api-key: ${{ secrets.NUGET_API_KEY }}