name: Release
on:
  pull_request:
    branches: "main"
    types: [closed]
  workflow_dispatch:
jobs:
  build_release:
    permissions:
      contents: write
    uses: jcdcdev/jcdcdev.Github.UmbracoSimpleDeploy/.github/workflows/build-release-template.yml@main
    with:
      project-name: 'jcdcdev.Umbraco.BackOfficeOrganiser'
      artifact-name: 'jcdcdev.Umbraco.BackOfficeOrganiser'
      project-path: './src/jcdcdev.Umbraco.BackOfficeOrganiser/jcdcdev.Umbraco.BackOfficeOrganiser.csproj'
      npm-enabled: true
      npm-working-dir: './src/jcdcdev.Umbraco.BackOfficeOrganiser.Client/'
      npm-run-command: 'build'
      deploy: true
    secrets:
      nuget-api-key: ${{ secrets.NUGET_API_KEY }}