name: 🔃 Sync branches

on:
  push:
    branches:
      - 'v*'
  workflow_dispatch:

jobs:
  check-branch:
    runs-on: ubuntu-latest
    outputs:
      is-valid-branch: ${{ steps.branch_check.outputs.is-valid-branch }}
    steps:
      - name: Check if branch name starts with 'v'
        id: branch_check
        run: |
          BRANCH_NAME=${{ github.ref }}
          if [[ $BRANCH_NAME == refs/heads/v* ]]; then
            echo "::set-output name=is-valid-branch::true"
          else
            echo "::set-output name=is-valid-branch::false"
            exit 1
          fi

  merge-branches:
    needs: check-branch
    if: needs.check-branch.outputs.is-valid-branch == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Merge into dev/v**
        run: |
          # Extract the version number from the branch name
          VERSION=$(echo "${GITHUB_REF}" | sed -n 's#refs/heads/v\([0-9]\+\)#\1#p')
          SOURCE_BRANCH="v${VERSION}"
          TARGET_BRANCH="dev/v${VERSION}"

          echo "Merging $SOURCE_BRANCH into $TARGET_BRANCH"

          # Checkout the source branch
          git checkout $SOURCE_BRANCH
          git pull origin $SOURCE_BRANCH
          echo "Pulled latest for $SOURCE_BRANCH"

          # Merge into the target branch
          git checkout $TARGET_BRANCH
          git merge --no-ff $SOURCE_BRANCH -m "Merge v$VERSION into dev/v$VERSION"
          echo "Merged $SOURCE_BRANCH into $TARGET_BRANCH"

          # Push changes
          git push origin $TARGET_BRANCH
          echo "Pushed changes to $TARGET_BRANCH"

